name: Migrate Bitbucket to GitHub

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Bitbucket repository
      run: |
        echo "Checking Bitbucket credentials..."
        
        echo "Cloning Bitbucket repository..."
        git clone https://arreyettaaugustine@bitbucket.org/bitbucket-migration-github/migration-repo.git bitbucket-repo || (echo "Failed to clone Bitbucket repository" && exit 1)

    - name: Push to GitHub repository
      run: |
        # Navigate to the cloned repository
        cd bitbucket-repo || (echo "Error: Cloned directory 'bitbucket-repo' not found" && exit 1)

        echo "Setting up GitHub remote..."

        # Ensure the script is running inside a Git repository
        if [ ! -d .git ]; then
          echo "Error: Not inside a Git repository. Aborting."
          exit 1
        fi

        # Show current remotes
        git remote -v  

        # Remove existing GitHub remote if it exists
        git remote remove github || true

        # Add GitHub remote with authentication
        git remote add github https://${{ secrets.GITHB_TOKEN }}@github.com/ARREYETTA14/Automated-Bitbucket-to-GitHub-Migration-with-GitHub-Actions.git

        # Verify remotes
        echo "Git remotes after adding GitHub:"
        git remote -v

        # Ensure the repository has commits before pushing
        if [ -z "$(git rev-list --all)" ]; then
          echo "Error: No commits found in the repository. Aborting push."
          exit 1
        fi

        # Push all branches and tags to GitHub
        echo "Pushing all branches to GitHub..."
        git push github --all || (echo "Failed to push branches" && exit 1)

        echo "Pushing all tags to GitHub..."
        git push github --tags || (echo "Failed to push tags" && exit 1)
      env:
        GITHB_TOKEN: ${{ secrets.GITHB_TOKEN }}
